openapi: 3.0.0
info:
  title: Firebase Functions API
  version: 1.0.0
  description: API for user login and client listing using Firebase
servers:
  - url: https://us-central1-biocryptricks.cloudfunctions.net/login
    description: Cloud Functions base URL
paths:
  /loginUser:
    post:
      summary: Login a user and list clients
      operationId: loginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "user@example.com"
                password:
                  type: string
                  example: "password123"
              required:
                - email
                - password
      responses:
        '200':
          description: Successful login and client listing
          content:
            application/json:
              schema:
                type: object
                properties:
                  uid:
                    type: string
                    example: "user-uid"
                  token:
                    type: string
                    example: "custom-token"
                  clients:
                    type: array
                    items:
                      type: object
                      additionalProperties: true
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: string
                example: "Email and password are required"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: string
                example: "Internal Server Error"